# Generated by Django 5.2.6 on 2026-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='availability',
        ),
        migrations.AddField(
            model_name='equipment',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('under_maintenance', 'Under Maintenance')], db_index=True, default='available', max_length=20),
        ),
    ]
