# Generated by Django 5.2.14 on 2026-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_equipment_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100, unique=True)),
                ('recommended_equipment', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_days', models.PositiveIntegerField()),
            ],
        ),
    ]
