# Generated by Django 5.2.14 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_recoverykit'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
