# Generated by Django 5.2.14 on 2026-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full medicine name including strength, e.g. Paracetamol 500mg', max_length=255)),
                ('brand', models.CharField(blank=True, default='', help_text='Manufacturer or brand name, e.g. Crocin, Dolo', max_length=255)),
                ('generic_name', models.CharField(blank=True, default='', help_text='Active ingredient name, e.g. Paracetamol', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('pain_relief', 'Pain Relief'), ('cold_and_flu', 'Cold & Flu'), ('digestive_health', 'Digestive Health'), ('vitamins', 'Vitamins & Supplements'), ('first_aid', 'First Aid'), ('skin_care', 'Skin Care'), ('eye_and_ear', 'Eye & Ear Care'), ('diabetes_care', 'Diabetes Care'), ('allergy', 'Allergy Relief'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('dosage_form', models.CharField(blank=True, default='', help_text='e.g. Tablet, Capsule, Syrup, Cream, Drops', max_length=100)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g. 500mg, 10ml, 5%', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit (strip, bottle, tube, etc.)', max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Number of units currently in stock')),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], db_index=True, default='in_stock', max_length=20)),
                ('requires_prescription', models.BooleanField(default=False, help_text='Always False for OTC items. Stored for future use.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive medicines are hidden from the public API.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacy/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
                'ordering': ['name'],
            },
        ),
    ]
