# Generated by Django 5.2.14 on 2026-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicineorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='paid', max_length=15),
        ),
    ]
