# Generated by Django 5.2.6 on 2026-07-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
