# Generated by Django 5.2.14 on 2026-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
